/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2019-09-04 11:30:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hcl.hib.College;
import com.hcl.hib.AddSubject;

public final class AddSubject_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.hcl.hib.AddSubject");
    _jspx_imports_classes.add("com.hcl.hib.College");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form method=\"post\" action=\"AddSubject.jsp\" name=\"productForm\">\r\n");
      out.write("\t\tSubject :\r\n");
      out.write("\t\t\t<select name=\"subject\" placeholder=\"please select one\" id=\"dropdown\" onchange=\"change()\">\r\n");
      out.write("\t\t\t\t<option value=\"Digital Communication\">Digital Communication</option>\r\n");
      out.write("\t\t\t\t<option value=\"Control Systems\">Control Systems</option>\r\n");
      out.write("\t\t\t\t<option value=\"Wireless Networks\">Wireless Networks</option>\r\n");
      out.write("\t\t\t\t<option value=\"Computer Networks\">Computer Networks</option>\r\n");
      out.write("\t\t\t\t<option value=\"Electromagnetic Theory\">Electromagnetic Theory</option>\r\n");
      out.write("\t\t\t\t<option value=\"Digital Signal Processing\">Digital Signal Processing</option>\r\n");
      out.write("\t\t\t\t<option value=\"Microprocessor\">Microprocessor</option>\r\n");
      out.write("\t\t\t</select><br/><br/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\tTheory :\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"theory\" id=\"theory\" readonly=\"readonly\"/><br/><br/>\r\n");
      out.write("\t\tPractical :\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"practical\" id=\"practical\" readonly=\"readonly\"/><br/><br/>\r\n");
      out.write("\t\tYear :\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"year\"/><br/><br/>\r\n");
      out.write("\t\tInstructor :\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"instructor\"/><br/><br/>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Click to Add\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("        function change(){\r\n");
      out.write("        var dval= document.getElementById(\"dropdown\").value;\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("        if(dval ==\"Digital Communication\"){\r\n");
      out.write("        \tproductForm.theory.value=\"42\";\r\n");
      out.write("        \tproductForm.practical.value=\"14\";\r\n");
      out.write("        }\r\n");
      out.write("        if(dval ==\"Control Systems\"){\r\n");
      out.write("        \t//alert(\"hi\");\r\n");
      out.write("        \tproductForm.theory.value=\"90\";\r\n");
      out.write("        \tproductForm.practical.value=\"50\";\r\n");
      out.write("        }\r\n");
      out.write("        if(dval ==\"Wireless Networks\"){\r\n");
      out.write("        \t//alert(\"hi\");\r\n");
      out.write("        \tproductForm.theory.value=\"69\";\r\n");
      out.write("        \tproductForm.practical.value=\"41\";\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if(dval ==\"Computer Networks\"){\r\n");
      out.write("        \t//alert(\"hi\");\r\n");
      out.write("        \tproductForm.theory.value=\"69\";\r\n");
      out.write("        \tproductForm.practical.value=\"41\";\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if(dval ==\"Electromagnetic Theory\"){\r\n");
      out.write("        \t//alert(\"hi\");\r\n");
      out.write("        \tproductForm.theory.value=\"107\";\r\n");
      out.write("        \tproductForm.practical.value=\"93\";\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if(dval ==\"Digital Signal Processing\"){\r\n");
      out.write("        \t//alert(\"hi\");\r\n");
      out.write("        \tproductForm.theory.value=\"84\";\r\n");
      out.write("        \tproductForm.practical.value=\"56\";\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if(dval ==\"Microprocessor\"){\r\n");
      out.write("        \t//alert(\"hi\");\r\n");
      out.write("        \tproductForm.theory.value=\"60\";\r\n");
      out.write("        \tproductForm.practical.value=\"0\";\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("        }\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("        ");

		if(request.getParameter("year") != null && 
			request.getParameter("instructor") != null &&
			request.getParameter("theory") != null && 
			request.getParameter("practical") != null &&
			request.getParameter("subject") != null) {
					AddSubject e=new AddSubject();
					e.setYear(Integer.parseInt(request.getParameter("year")));
					e.setInstructor(request.getParameter("instructor"));
					e.setTheory(Integer.parseInt(request.getParameter("theory")));
					e.setPractical(Integer.parseInt(request.getParameter("practical")));
					e.setSubject(request.getParameter("subject"));
					College crud=new College();
					out.println(crud.insertSubject(e));
				}
        
	
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</body>\r\n");
      out.write("\t\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
